version: '3.7'

networks:
  laravel:

services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - ./src:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d
    depends_on:
      - app
      - mysql
    networks: 
      - laravel

  mysql:
    restart: always
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  app:
    restart: always
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - laravel

  node:
    restart: always
    build:
      context: docker/node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./src:/var/www/